<?php
include 'includes/header.php'
?>
<section>
	<div class="interior">
		<article> <span class="titulo">
			<h1>ASPECTOS LEGALES Y POLITICAS DE PRIVACIDAD</h1>
			</span>
			<p>Este sitio web ha sido creado por Motor Mundo S.A. (en adelante Motormundo) con carácter informativo y para uso personal. Accediendo a este sitio web y a la información que en él se presenta el usuario acepta las siguientes cláusulas que a continuación se indican y que definen los términos, condiciones y política de privacidad del presente sitio web y de todas sus funcionalidades, contenidos e información que en él aparecen.</p>
			<h3><strong>Aspectos generales</strong></h3>
			<p>El acceso a este sitio web y a sus funcionalidades es responsabilidad exclusiva de los usuarios. El simple acceso a este sitio web no supone entablar ningún tipo de relación de carácter comercial entre Motormundo y el usuario. El acceso y navegación en este sitio web supone aceptar y conocer las advertencias legales, condiciones y términos de uso contenidas en ella. La información que aparece en este sitio web es la vigente en la fecha de su última actualización. Por regla general, el sitio web es solamente informativo, y las relaciones contractuales que deriven de la información que recibe el usuario requerirán de su confirmación por escrito por parte de Motormundo, todo ello de conformidad con la Ley de Protección de Datos Personales (Ley Nº 29733).</p>
			<h3><strong>Modificación de la información</strong></h3>
			<p>Motormundo se reserva la facultad y el derecho de actualizar, modificar o eliminar contenido o información de este sitio web que estime conveniente, en parte o en su totalidad, pudiendo hacer uso de tal facultad en cualquier momento y sin previo aviso. Este derecho abarca los contenidos referidos a disponibilidad de modelos, colores, especificaciones, precio, disponibilidad de productos o servicios, equipamiento o en cuanto a las funcionalidades del sitio o de la información de actividades promocionales.</p>
			<p>Motormundo se reserva la facultad de modificar unilateralmente las condiciones y términos de uso de este sitio web. La entrada en vigor de las modificaciones de las condiciones de uso se producirá desde el momento de su publicación en este sitio web.</p>
			<h3><strong>Contenidos</strong></h3>
			<p>Los datos técnicos y de equipamiento de los vehículos están sujetos a permanentes modificaciones. Aunque se trata de mantener los contenidos actualizados, las fichas técnicas o cualquier contenido referido a los equipamientos o accesorios que se incluyen en esta página Web no deberán considerarse como guía exacta de las especificaciones de un vehículo determinado, dichos equipamientos o accesorios serán referenciales. Para mayor información, deberá dirigirse a la red de venta autorizada donde le informarán sobre los equipamientos y especificaciones exactas de los modelos disponibles.</p>
			<p>Motormundo se reserva el derecho de modificar las especificaciones, precios, colores y equipamientos de sus vehículos sin previo aviso, según el stock disponible.</p>
			<p>Los colores de los vehículos que se muestran en esta página Web son referenciales e intentan dar una idea aproximada de la gama disponibles. Los colores disponibles al momento de compra pueden ser distintos a los que se muestran en esta página Web ya que ellos dependen del stock disponible al momento de la compra. Por ello, estos pueden variar sin previo aviso.</p>
			<p>Este sitio contiene información relativa a los productos y los servicios, las actividades que Motormundo realiza, a las actividades promocionales vigentes con sus respectivas fechas de inicio y caducidad, y contenidos propios de las áreas de Servicio Técnico, Repuestos y a otras actividades que le son propia en su gestión comercial.</p>
			<p>Algunas imágenes que se incluyen en este sitio, ya sean fotografías o videos, pueden no corresponder con exactitud a las versiones o equipamientos de modelos importados por Motormundo. Ellas son solo de carácter ilustrativos o referenciales y no implican obligatoriedad para Motormundo de disponer de estos modelos ni podrán ser exigidas por los usuarios del sitio web.</p>
			<p>Los productos y servicios, las funcionalidades y las promociones que Motormundo describen en este sitio web están ofrecidos únicamente para el territorio nacional y solamente podrán entregarla a través de la amplia Red de puntos de ventas propios o de concesionarios autorizados.</p>
			<p>Motormundo realiza los máximos esfuerzos para evitar cualquier error en los contenidos que pudieran aparecer en este sitio Web; sin embargo no garantiza, ni se responsabiliza de las consecuencias que pudieran derivarse de los errores en los contenidos que pudieran aparecer.</p>
			<p>En caso de discrepancia entre la versión impresa de los materiales (folletería, catálogo o cualquier otro documento) y la publicada en el sitio Web, prevalecerá la versión impresa, salvo lo establecido respecto a erratas y actualizaciones.</p>
			<p>Las informaciones, contenidos y datos de cualquier especie que estén incluidos en éste sitio Web se revisan antes de su publicación; sin embargo, no es posible garantizar que se encuentren absolutamente libres de erratas, errores mecanográficos, defectos de composición y problemas equivalentes, por lo que Motormundo recomienda a los usuarios que estén atentos a las posibles actualizaciones o rectificaciones que el sitio Web incorpore, que confirmen los datos que resulten de interés esencial para ellos a través de los cauces de comunicación personal, telefónica o por fax que se proporcionan en este mismo sitio y en los medios de comunicación y que en ningún caso adopten decisiones basadas única o especialmente en la información del sitio web.</p>
			<p>Errores tipográficos: Todos las actividades promocionales publicados por Motormundo en cualquier soporte publicitario, propio o de terceros, especialmente los referentes a banners, comunicaciones electrónicas por e-mail, o cualquier otro, y que contengan algún error tipográfico ya sea involuntario o por manipulación de terceros, carecen de todo valor, y en caso de duda se recomienda que los usuarios confirmen los datos a través de canales personales como el fax o teléfono, bien por medio de Motormundo o su red de concesionarios autorizados.</p>
			<h3><strong>Fin informativo y relacional</strong></h3>
			<p>Toda la información incluida en este sitio web tiene fines informativos y de carácter relacional para facilitar a los usuarios informarse de los productos y acceder a servicios que Motormundo ofrece en lo relativo a reservas de hora, cotizaciones o contactos con áreas específicas de la empresa. Este sitio no debe ser usado o entendido como sustituto de la información que le facilite la red de puntos de venta de Motormundo o de la red concesionarios autorizados. Motormundo realiza los máximos esfuerzos para que las funcionalidades relacionales se realice en las mejores condiciones posibles y que estén siempre disponibles, en funcionamiento y evitando perjuicios de cualquier tipo que pudiesen ocasionarse durante la misma.</p>
			<h3><strong>Precio de los Productos</strong></h3>
			<p>Los precios son los recomendados de venta al público, por lo que los precios finales que ofrezca un punto de venta de la red de Motormundo o sus concesionarios autorizados pueden ser distintos. La compra de cualquier producto está sujeto a los términos y condiciones fijados en cada contrato de compraventa.</p>
			<p>Se entiende por “contrato de compraventa” el conjunto de documentos mercantiles (factura por vehículo nuevo y sin uso, guía de despacho, póliza de garantía del fabricante) que dan cuenta física de la celebración del contrato de compraventa.</p>
			<h3><strong>Links en el sitio web</strong></h3>
			<p>Motormundo no se responsabiliza en modo alguno de aquellos contenidos, actividades comerciales, productos y servicios incluidos que pudiesen visualizarse mediante enlaces electrónicos (links), directa o indirectamente, a través de este sitio web, en especial los que pudieran corresponder a contenidos de valor agregado para el usuario, como de ocio, entretenimiento, curiosidades, consejos u otros.</p>
			<p>La presencia de links en el sitio web de Motormundo salvo manifestación expresa en contrario, tiene una finalidad meramente informativa y en ningún caso supone sugerencia, invitación o recomendación sobre los mismos. Estos enlaces no representan ningún tipo de relación entre Motormundo y los particulares o empresas titulares de los sitios web a los que puede accederse mediante estos enlaces. Motormundo se reserva el derecho de retirar de modo unilateral y en cualquier momento los links que aparecen en este sitio web.</p>
			<h3><strong>Navegación, acceso y seguridad</strong></h3>
			<p>El acceso y navegación en este sitio web supone aceptar y conocer las advertencias legales, condiciones y términos de uso contenidas en ella. Motormundo realiza los máximos esfuerzos para que la navegación se realice en las mejores condiciones y evitar los perjuicios de cualquier tipo que pudiesen ocasionarse durante la misma.</p>
			<p>Motormundo no se responsabiliza ni garantiza que el acceso a este sitio web sea ininterrumpido o que esté libre de error, ni por las fallas en rendimiento, omisiones, interrupciones de servicio, defectos, demoras en la transmisión o fallas en las líneas de conexión. Tampoco se responsabiliza o garantiza que el contenido o software al que pueda accederse a través de este sitio web, esté libre de error o cause un daño.</p>
			<p>En ningún caso Motormundo será responsable por las pérdidas, daños o perjuicios de cualquier tipo que surjan por el acceso y el uso del sitio web, incluyéndose pero no limitándose, a los ocasionados a los sistemas informáticos o los provocados por la introducción de virus. Motormundo no se hace responsable de los daños que pudiesen ocasionarse a los usuarios por un uso inadecuado de este sitio web.</p>
			<h3><strong>Propiedad intelectual</strong></h3>
			<p>Este sitio web y los contenidos que alberga se encuentran protegidos por las leyes de Propiedad industrial e Intelectual, inclusive de los incluidos en tratados internacionales ratificados por Perú. No podrán ser objeto de explotación, reproducción, distribución, modificación, comunicación pública, cesión o transformación. El acceso a este sitio web no otorga a los usuarios derecho, ni titularidad alguna sobre los derechos de propiedad intelectual de los contenidos que alberga este sitio web.</p>
			<p>El contenido de este sitio web puede ser descargado al terminal del usuario (download) siempre que sea para su uso privado inmediato y sin ningún fin comercial; por lo tanto no podrá explotar, reproducir, distribuir, modificar, comunicar públicamente, ceder, transformar o usar el contenido de este sitio web con fines públicos o comerciales.</p>
			<p>Motormundo no transfiere a los usuarios la propiedad de su software. El usuario es el propietario del soporte en el cual es software es grabado. Motormundo retiene todos los derechos de propiedad industrial e intelectual incluyendo el software. Si el usuario transfiere software de este sitio web a su terminal, no podrá diseccionarlo para su estudio, o descompilarlo, traducir la versión del código objeto original o su lenguaje a otro código o lenguaje.</p>
			<h3><strong>Marcas registradas</strong></h3>
			<p>Todas las marcas, logotipos y anagramas mostrados en este sitio son propiedad de Motormundo o de terceras empresas ligadas. Se prohíbe usarlos, descargarlos permanentemente, copiarlos o distribuirlos por cualquier medio sin el permiso escrito de Motormundo o de la tercera empresa.</p>
			<h3><strong>Acciones judiciales</strong></h3>
			<p>Motormundo se reserva la posibilidad de ejercer las acciones judiciales que correspondan contra los usuarios que violen o infrinjan los derechos de propiedad intelectual e industrial.</p>
			<h3><strong>Política de Privacidad</strong></h3>
			<p>Datos personales: La finalidad y el uso de los datos que usted proporcione a Motormundo viene recogida en el texto legal de aquel formulario que complete en este sitio web.</p>
			<p>La visita a este sitio web no supone que el usuario esté obligado a facilitar ninguna información sobre sí mismo. En el caso de que proporcione el usuario alguna información de carácter personal, los datos recogidos en este sitio web serán utilizados con la finalidad, en la forma y con las limitaciones y derechos que recoge la Ley de Protección de Datos Personales (Ley Nº 29733).</p>
			<p>Los usuarios que faciliten datos de carácter personal, consienten inequívocamente la incorporación de sus datos en una base de datos de los que será responsable Motormundo, así como el tratamiento o no de los mismos. Esta información será tratada con sumo cuidado y con la mayor seguridad posible y sólo se utilizará de acuerdo a los límites establecidos en este documento.</p>
			<p>Los datos de registro deberán ser veraces. Motormundo sólo reúne datos personales cuando estos son proporcionados directamente por el usuario.</p>
			<p>Motormundo procederá a la cancelación de los datos recogidos cuando dejen de ser necesarios o pertinentes para la finalidad para la que hubiesen sido recabados o registrados.</p>
			<p>En el caso de que los datos recogidos se utilizasen para una finalidad distinta para la cual hubiesen sido recabados o recogidos se requerirá el consentimiento previo de los interesados.</p>
			<p>Motormundo utiliza los datos que proporcionan los usuarios para los fines directos por los cuales se entregan y para difundir ofertas de productos o de servicios, para informar novedades de productos o servicios que podrían ser de utilidad e interés y para personalizar y mejorar la relación con sus clientes.</p>
			<p>Cada vez que el usuario ingresa sus datos, deberá aceptar o rechazar el uso en futuras comunicaciones. Al completar cualquier formulario, si no está de acuerdo con esto, el usuario deberá desactivar la opción respectiva. Si elige mantenerla activada autoriza a Motormundo al uso de los datos con los objetivos antes expuestos.</p>
			<p>Motormundo ha adoptado las medidas técnicas y organizativas necesarias para garantizar la seguridad e integridad de los datos, así como para evitar su alteración, pérdida, tratamiento o acceso no autorizado. No obstante, en la actualidad ningún sistema es completamente seguro o libre de ataques.</p>
			<p>Los usuarios cuyos datos sean objeto de tratamiento podrán ejercitar gratuitamente los derechos de oposición, acceso, información, rectificación, cancelación y tratamiento objetivo de sus datos personales, sin efectos retroactivos según los términos especificados en la Ley de Protección de Datos Personales (Ley Nº 29733), conforme al procedimiento legalmente establecido. Estos derechos podrán ser ejercitados dirigiendo una solicitud vía e-mail a atencioncliente@agildemeister.com.pe, haciendo uso del formato previsto por la empresa para estos efectos.</p>
			<p>El acceso a este sitio web puede implicar la utilización de cookies. Las cookies son pequeñas cantidades de información que se almacenan en el navegador utilizado por cada usuario para que el servidor recuerde cierta información que posteriormente únicamente el servidor que la implementó leerá. Las cookies tienen, generalmente, una duración limitada en el tiempo. Ninguna cookie de este sitio web permite que pueda contactarse con el número de teléfono del usuario, su dirección de correo electrónico o con cualesquiera otro medio de contacto. Ninguna cookie de este sitio web puede extraer información del disco duro del usuario o robar información personal. La única manera, en este sitio web, de que la información privada de un usuario forme parte del archivo cookie es que el usuario dé personalmente esa información al servidor. Aquellos usuarios que no deseen recibir cookies o quieran ser informados de su fijación pueden configurar su navegador a tal efecto.</p>
			<h3><strong>Jurisdicción y legislación aplicable</strong></h3>
			<p>Los términos y condiciones que rigen este sitio Web y todas las relaciones que pudieran derivarse se encuentran salvaguardados por la legislación peruana.</p>
			<p>Cualquier controversia que pudiera derivarse del acceso o la utilización de este sitio Web se somete a la exclusiva jurisdicción de los tribunales de Lima (Perú).</p>
		</article>
	</div>
</section>
<?php
include 'includes/footer.php'
?>